example:
	docker run -d --name php_mod_wasm_example -p8000:8080 -v ${HOME}/php-example:/usr/local/apache2/htdocs projects.registry.vmware.com/wasmlabs/containers/php-mod-wasm:hello-world 2> /dev/null

wordpress:
	docker run -d --name php_mod_wasm_wordpress -p8080:8080 projects.registry.vmware.com/wasmlabs/containers/php-mod-wasm:wordpress 2> /dev/null
